source 'https://rubygems.org'

group :rake do
  gem 'rake', '~> 12.0'
end

group :lint do
  gem 'foodcritic', '~> 9.0'
  gem 'rubocop', '~> 0.47'
end

group :unit do
  gem 'berkshelf', '~> 5.6'
  gem 'cookstyle', '~> 1.3'
end

group :kitchen do
  gem 'test-kitchen', '~> 1.16'
  gem 'kitchen-vagrant', '~> 0.19'
end
